services:
  api:
    build:
      context: ./app/app
      dockerfile: Dockerfile
    container_name: nextleads_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15
    container_name: nextleads_postgres
    environment:
      POSTGRES_DB: nextleads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: nextleads_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always
