services:
  api:
    build:
      context: ./app/app
      dockerfile: Dockerfile
    container_name: nextleads_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nextleads
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: "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"
      UNIPILE_API_KEY: "V3V8fANL./k2OSAm6EO2/Jqh9/1bvMLne0DzzSVmgNzEigkUWdWI="
      UNIPILE_DSN: "api42.unipile.com:17201"
      UNIPILE_ACCOUNT_ID: "a44F-7bFQqifQUC_YkEPug"
      ZAPI_INSTANCE_ID: "3F260EE9DC7C32D89253D217A5857A3E"
      ZAPI_TOKEN: "B0935FE55592AFF41073FF91"
      ZAPI_CLIENT_TOKEN: "F8049ba5dda10471b879715c0e5abfb54S"
      DEFAULT_SDR_ID: "458be506-c784-43ba-9e47-f2fd7c646dbe"
      INTERNAL_API_SECRET: "nextleads-secret-2026"
      GLOBAL_ALERT_GROUP_ID: "120363402768321532-group"
      IGNORE_BUSINESS_HOURS: "true"

    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15
    container_name: nextleads_postgres
    environment:
      POSTGRES_DB: nextleads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: nextleads_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always
